char *balloonist_names[] = { // 0x8006F880
  "RETURN HOME",
  "MARCO",
  "GOSNOLD",
  "TUCO",
  "CRAY",
  "AMOS",
  "HAK",
};

char *homeworld_names[] = { // 0x8006F7D4
  "ARTISANS",
  "PEACE KEEPERS",
  "MAGIC CRAFTERS",
  "BEAST MAKERS",
  "DREAM WEAVERS",
  "GNASTY'S WORLD",
  "THIGH MASTERS",
};

char *level_names[] = { // 0x8006F7F0
  "HOME",
  "STONE HILL",
  "DARK HOLLOW",
  "TOWN SQUARE",
  "TOASTY",
  "SUNNY FLIGHT",
  "HOME",
  "DRY CANYON",
  "CLIFF TOWN",
  "ICE CAVERN",
  "DOCTOR SHEMP",
  "NIGHT FLIGHT",
  "HOME",
  "ALPINE RIDGE",
  "HIGH CAVES",
  "WIZARD PEAK",
  "BLOWHARD",
  "CRYSTAL FLIGHT",
  "HOME",
  "TERRACE VILLAGE",
  "MISTY BOG",
  "TREE TOPS",
  "METALHEAD",
  "WILD FLIGHT",
  "HOME",
  "DARK PASSAGE",
  "LOFTY CASTLE",
  "HAUNTED TOWERS",
  "JACQUES",
  "ICY FLIGHT",
  "GNORC GNEXUS",
  "GNORC COVE",
  "TWILIGHT HARBOR",
  "GNASTY GNORC",
  "GNASTY'S LOOT",
  "A",
};

char *dragon_names[] = {
  "SILVUS",
  "ARGUS",
  "DELBIN",
  "NESTOR",
  "LINDAR",
  "GILDAS",
  "ASTOR",
  "GAVIN",
  "OSWIN",
  "DARIUS",
  "ALBAN",
  "NILS",
  "DEVLIN",
  "TOMAS",
  "ALVAR",
  "NEVIN",
  "MAGNUS",
  "GUNNAR",
  "TITAN",
  "BORIS",
  "MAXIMOS",
  "CONAN",
  "IVOR",
  "THOR",
  "MARCO",
  "ENZO",
  "HALVOR",
  "GALE",
  "ANDOR",
  "RAGNAR",
  "ULRIC",
  "TODOR",
  "ASHER",
  "TRONDO",
  "COSMOS",
  "ZANTOR",
  "BOLDAR",
  "ZANE",
  "ELDRID",
  "KELVIN",
  "ZANDER",
  "CYRUS",
  "AJAX",
  "CEDRIC",
  "HEXUS",
  "JARVIS",
  "LUCAS",
  "ALTAIR",
  "FINLAY",
  "JETHRO",
  "BRUNO",
  "CLEETUS",
  "CLAUDE",
  "CYPRIN",
  "ROSCO",
  "DAMON",
  "BUBBA",
  "ZEKE",
  "ISAAK",
  "LYLE",
  "JED",
  "SADIKI",
  "ZIKOMO",
  "MAZI",
  "LATEEF",
  "KASIYA",
  "AZIZI",
  "BAKARI",
  "APARA",
  "OBASI",
  "USENI",
  "BARUTI",
  "MUDADA",
  "KOSOKO",
  "COPANO",
  "LUTALO",
  "UNIKA",
  "RASHIDI",
  "REVILO",
  "DRAGON X",
};

/*
union color15 colors[] = { // 0x8006F310
  {.r = 0x00, .g = 0x01, .b = 0x00},
  {.r = 0x01, .g = 0x01, .b = 0x01},
  {.r = 0x02, .g = 0x02, .b = 0x02},
  {.r = 0x03, .g = 0x03, .b = 0x03},
  {.r = 0x04, .g = 0x04, .b = 0x04},
  {.r = 0x05, .g = 0x05, .b = 0x05},
  {.r = 0x06, .g = 0x06, .b = 0x06},
  {.r = 0x07, .g = 0x07, .b = 0x07},
  {.r = 0x08, .g = 0x08, .b = 0x08},
  {.r = 0x09, .g = 0x09, .b = 0x09},
  {.r = 0x0A, .g = 0x0A, .b = 0x0A},
  {.r = 0x0B, .g = 0x0B, .b = 0x0B},
  {.r = 0x0C, .g = 0x0C, .b = 0x0C},
  {.r = 0x0D, .g = 0x0D, .b = 0x0D},
  {.r = 0x0E, .g = 0x0E, .b = 0x0E},
  {.r = 0x0F, .g = 0x0F, .b = 0x0F},
  {.r = 0x10, .g = 0x10, .b = 0x10},
  {.r = 0x11, .g = 0x11, .b = 0x11},
  {.r = 0x12, .g = 0x12, .b = 0x12},
  {.r = 0x13, .g = 0x13, .b = 0x13},
  {.r = 0x14, .g = 0x14, .b = 0x14},
  {.r = 0x15, .g = 0x15, .b = 0x15},
  {.r = 0x16, .g = 0x16, .b = 0x16},
  {.r = 0x17, .g = 0x17, .b = 0x17},
  {.r = 0x18, .g = 0x18, .b = 0x18},
  {.r = 0x19, .g = 0x19, .b = 0x19},
  {.r = 0x1A, .g = 0x1A, .b = 0x1A},
  {.r = 0x1B, .g = 0x1B, .b = 0x1B},
  {.r = 0x1C, .g = 0x1C, .b = 0x1C},
  {.r = 0x1D, .g = 0x1D, .b = 0x1D},
  {.r = 0x1E, .g = 0x1E, .b = 0x1E},
  {.r = 0x1F, .g = 0x1F, .b = 0x1F},
};
*/