#pragma once

#include <stdint.h>

#define LIB_TITLE_SCREEN 0
#define LIB_ARTISANS_HOME 1
#define LIB_STONE_HILL 2
#define LIB_DARK_HOLLOW 3
#define LIB_TOASTY 4
#define LIB_SUNNY_FLIGHT 5
#define LIB_TOWN_SQUARE 6
#define LIB_PEACEKEEPERS_HOME 7
#define LIB_CLIFF_TOWN 8
#define LIB_ICE_CAVERN 9
#define LIB_DRY_CANYON 10
#define LIB_DR_SHEMP 11
#define LIB_NIGHT_FLIGHT 12
#define LIB_MAGICCRAFTERS_HOME 13
#define LIB_ALPINE_RIDGE 14
#define LIB_HIGH_CAVES 15
#define LIB_CRYSTAL_FLIGHT 16
#define LIB_WIZARD_PEAK 17
#define LIB_BLOWHARD 18
#define LIB_BEASTMAKERS_HOME 19
#define LIB_TERRACE_VILLAGE 20
#define LIB_MISTY_BOG 21
#define LIB_TREE_TOPS 22
#define LIB_WILD_FLIGHT 23
#define LIB_METALHEAD 24
#define LIB_DREAMWEAVERS_HOME 25
#define LIB_DARK_PASSAGE 26
#define LIB_HAUNTED_TOWERS 27
#define LIB_ICY_FLIGHT 28
#define LIB_LOFTY_CASTLE 29
#define LIB_JACQUES 30
#define LIB_GNASTYS_WORLD 31
#define LIB_GNORC_COVE 32
#define LIB_TWILIGHT_HARBOR 33
#define LIB_GNASTY_GNORC 34
#define LIB_CREDITS 35
#define LIB_GNASTYS_LOOT 36

extern uint32_t lib_num;