#pragma once

#include <stdint.h>

#define LIB_TITLE_SCREEN 0
#define LIB_ARTISANS_HOME 10
#define LIB_STONE_HILL 11
#define LIB_DARK_HOLLOW 12
#define LIB_TOWN_SQUARE 13
#define LIB_TOASTY 14
#define LIB_SUNNY_FLIGHT 15
#define LIB_PEACEKEEPERS_HOME 20
#define LIB_DRY_CANYON 21
#define LIB_CLIFF_TOWN 22
#define LIB_ICE_CAVERN 23
#define LIB_DR_SHEMP 24
#define LIB_NIGHT_FLIGHT 25
#define LIB_MAGICCRAFTERS_HOME 30
#define LIB_ALPINE_RIDGE 31
#define LIB_HIGH_CAVES 32
#define LIB_WIZARD_PEAK 33
#define LIB_BLOWHARD 34
#define LIB_CRYSTAL_FLIGHT 35
#define LIB_BEASTMAKERS_HOME 40
#define LIB_TERRACE_VILLAGE 41
#define LIB_MISTY_BOG 42
#define LIB_TREE_TOPS 43
#define LIB_METALHEAD 44
#define LIB_WILD_FLIGHT 45
#define LIB_DREAMWEAVERS_HOME 50
#define LIB_DARK_PASSAGE 51
#define LIB_LOFTY_CASTLE 52
#define LIB_HAUNTED_TOWERS 53
#define LIB_JACQUES 54
#define LIB_ICY_FLIGHT 55
#define LIB_GNASTYS_WORLD 60
#define LIB_GNORC_COVE 61
#define LIB_TWILIGHT_HARBOR 62
#define LIB_GNASTY_GNORC 63
#define LIB_GNASTYS_LOOT 64
#define LIB_CREDITS 65

extern uint32_t lib_num;